#!/bin/bash

[ -n "$PS1" ] \
    && . ~/.bash_profile

eval $(thefuck --alias)

[ -f /usr/local/etc/profile.d/autojump.sh ] && . /usr/local/etc/profile.d/autojump.sh

[ -f /usr/share/autojump/autojump.sh ] && . /usr/share/autojump/autojump.sh
